version: "3.7"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  logreader:
    image: sharmavijay1991/logreader
    ports:
      - "8082"
    depends_on:
      - mongo

  logwriter:
    image: sharmavijay1991/logwriter
    ports:
      - "8081"
    depends_on:
      - mongo

