pipeline {
  agent any
  tools{
    maven 'maven 3.6.1'
  }
  
  stages{
    stage("build"){
      steps{
        echo 'Compiling users app..'
        dir('cmad-log-reader'){
          sh 'mvn compile'
        }
      }
    }
    stage("test"){
      steps{
        echo 'No testcases available'
      }
    }
     stage("package"){
      steps{
        echo 'Packaging user app'
        dir('cmad-log-reader'){
          sh 'mvn  package -DskipTests'
          archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
        }
      }
    }
     stage("docker-package"){ 
        steps{
           echo 'Packaging log-reader app with docker'
           script
           {
        	  docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') 
        	  {
        		  def usersImage = docker.build("sharmavijay1991/logreader:v${env.BUILD_ID}", "cmad-log-reader")
        		  usersImage.push()
        		  usersImage.push("latest")
        	  }
		   }
	    }
     }
  }
  post{
    always{
      echo 'Writer compilation is complete...'
    }
  }
}